project_name: opentelemetry-collector-components
builds:
- id: otel-grafana
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ignore:
  - goos: darwin
    goarch: "386"
  - goos: windows
    goarch: arm64
  dir: distributions/otel-grafana/_build
  binary: otel-grafana
  ldflags:
  - -s
  - -w
  flags:
  - -trimpath
  env:
  - CGO_ENABLED=0
archives:
- id: otel-grafana
  builds:
  - otel-grafana
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
- package_name: otel-grafana
  contents:
  - src: distributions/otel-grafana/otel-grafana.service
    dst: /lib/systemd/system/otel-grafana.service
  - src: distributions/otel-grafana/otel-grafana.conf
    dst: /etc/otel-grafana/otel-grafana.conf
    type: config|noreplace
  - src: configs/otel-grafana.yaml
    dst: /etc/otel-grafana/config.yaml
    type: config
  scripts:
    preinstall: distributions/otel-grafana/preinstall.sh
    postinstall: distributions/otel-grafana/postinstall.sh
    preremove: distributions/otel-grafana/preremove.sh
  id: otel-grafana
  builds:
  - otel-grafana
  formats:
  - apk
  - deb
  - rpm
  maintainer: The OpenTelemetry Team @ Grafana Labs <opentelemetry@grafana.com>
  description: Grafana Lab's otel-grafana distribution of the OpenTelemetry Collector
  license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
- goos: linux
  goarch: amd64
  dockerfile: distributions/otel-grafana/Dockerfile
  image_templates:
  - ghcr.io/grafana/opentelemetry-collector-components/otel-grafana:{{ .Version }}-amd64
  extra_files:
  - configs/otel-grafana.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/amd64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
docker_manifests:
- name_template: ghcr.io/grafana/opentelemetry-collector-components/otel-grafana:{{
    .Version }}
  image_templates:
  - ghcr.io/grafana/opentelemetry-collector-components/otel-grafana:{{ .Version }}-amd64
