name: Continuous Integration - GoReleaser

on:
  push:
    branches: [main]
    paths:
    - ".goreleaser.yaml"
    - "distributions/otlp-gateway/manifest.yaml"
    - "distributions/sidecar/manifest.yaml"
    - "distributions/tracing/manifest.yaml"
  pull_request:
    branches: [main]
    paths:
    - ".goreleaser.yaml"
    - "distributions/otlp-gateway/manifest.yaml"
    - "distributions/sidecar/manifest.yaml"
    - "distributions/tracing/manifest.yaml"

jobs:
  check-goreleaser:
    name: Check GoReleaser Configuration
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Argo
        run: |
          DOCKER_TAG=123
          COMMIT_AUTHOR=${{github.actor}}
          COMMIT_LINK=${{github.event.compare}}
          COMMAND="submit --from workflowtemplate/deploy-otlp-gateway-v2 --name otlp-gateway-v2-deploy-${DOCKER_TAG} --parameter dockertag=${DOCKER_TAG} --parameter commit=${GITHUB_SHA} --parameter commit_author=${COMMIT_AUTHOR} --parameter commit_link=${COMMIT_LINK}"
          cat << EOF
          Triggering argo-workflows ci-goreleaser:
          - command="$COMMAND"
          EOF
