name: Continuous Integration - GoReleaser

on:
  push:
    branches: [main]
    paths:
    - ".goreleaser.yaml"
    - "distributions/otlp-gateway/manifest.yaml"
    - "distributions/sidecar/manifest.yaml"
    - "distributions/tracing/manifest.yaml"
  pull_request:
    branches: [main]
    paths:
    - ".goreleaser.yaml"
    - "distributions/otlp-gateway/manifest.yaml"
    - "distributions/sidecar/manifest.yaml"
    - "distributions/tracing/manifest.yaml"

jobs:
  check-goreleaser:
    name: Check GoReleaser Configuration
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Argo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          cat << EOF
          Triggering argo-workflows ci-goreleaser:
          - context="$GITHUB_CONTEXT"
          EOF

