name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Argo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          cat << EOF
          Triggering argo-workflows:
          - context="$GITHUB_CONTEXT"
          EOF
