name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Argo
        run: |
          DOCKER_TAG=123
          COMMIT_AUTHOR=${{github.actor}}
          COMMIT_LINK=${{github.event.compare}}
          COMMAND="submit --from workflowtemplate/deploy-otlp-gateway-v2 --name otlp-gateway-v2-deploy-${DOCKER_TAG} --parameter dockertag=${DOCKER_TAG} --parameter commit=${GITHUB_SHA} --parameter commit_author=${COMMIT_AUTHOR} --parameter commit_link=${COMMIT_LINK}"
          cat << EOF
          Triggering argo-workflows ci-goreleaser:
          - command="$COMMAND"
          EOF
